# Generated by Django 2.1.7 on 2019-10-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolepermission',
            table='bm_access_control_role_permission',
        ),
        migrations.AlterModelTable(
            name='roleuser',
            table='bm_access_control_role_user',
        ),
    ]
