# Generated by Django 2.1.7 on 2019-10-22 17:19

import common.lark_common.random_object_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_auto_20191021_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='uuid',
            field=models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='uuid', max_length=64),
        ),
        migrations.AddField(
            model_name='permission',
            name='disabled',
            field=models.BooleanField(blank=True, help_text='显示控制', null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='uuid',
            field=models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='uuid', max_length=64),
        ),
        migrations.AddField(
            model_name='role',
            name='uuid',
            field=models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='uuid', max_length=64),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='uuid',
            field=models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='uuid', max_length=64),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='uuid',
            field=models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='uuid', max_length=64),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('saber', 'saber'), ('url', 'url'), ('navbar', 'navbar'), ('button', 'button')], help_text='元素类型', max_length=32),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], help_text='授权动作', max_length=64),
        ),
    ]
