# Generated by Django 2.1.7 on 2019-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_auto_20191022_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='info',
            field=models.TextField(blank=True, help_text='备用信息', null=True),
        ),
    ]
