# Generated by Django 2.1.7 on 2019-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_element_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='role',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('sidebar', 'sidebar'), ('url', 'url'), ('navbar', 'navbar'), ('button', 'button')], help_text='元素类型', max_length=32),
        ),
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.CharField(choices=[('element', 'element')], help_text='权限的类型', max_length=64),
        ),
    ]
