# Generated by Django 2.1.7 on 2019-10-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_auto_20191028_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='角色名称', max_length=64, unique=True),
        ),
    ]
