# Generated by Django 2.1.7 on 2019-10-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_nonemeta_responsenonemeta'),
        ('access_control', '0007_auto_20191029_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('permission', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='roleuser',
            unique_together={('user', 'role')},
        ),
    ]
