# Generated by Django 2.1.7 on 2019-10-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_auto_20191031_1417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('owner_path', 'element_id', 'type')},
        ),
    ]
