# Generated by Django 2.1.7 on 2019-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0012_auto_20191107_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='角色名称', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='owner',
            field=models.CharField(blank=True, help_text='专有角色关联', max_length=128, null=True),
        ),
    ]
