# Generated by Django 2.1.7 on 2019-10-21 14:34

import common.lark_common.random_object_id
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmContract',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='合同ID。示例：5d5faf299cf80f024abdf787', max_length=64, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, help_text='公司ID。示例：5d5faf299cf80f024abdf787', max_length=64, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='公司名称。示例：5d5faf299cf80f024abdf787', max_length=255, null=True)),
                ('contract_number', models.CharField(help_text='合同编码。示例：ECBM004', max_length=64)),
                ('authorizer', models.CharField(blank=True, help_text='授权人。示例：魏一二', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, help_text='合同开始时间。示例：2019-09-29', null=True)),
                ('expire_date', models.DateField(blank=True, help_text='合同终止时间。示例：2029-09-29', null=True)),
                ('contract_type', models.CharField(blank=True, help_text='合同类型。示例：标准合同/框架合同', max_length=64, null=True)),
                ('payment_date', models.IntegerField(blank=True, help_text='账期天数。示例：4/100', null=True)),
                ('contract_value', models.BigIntegerField(blank=True, help_text='月金额（元）。示例：3000', null=True)),
                ('status', models.CharField(blank=True, help_text='合同状态。示例：active/terminated', max_length=255, null=True)),
                ('create_at', models.DateTimeField(blank=True, help_text='创建时间。示例：2019-09-29 09:33:17', null=True)),
                ('update_at', models.DateTimeField(blank=True, help_text='更新时间。示例：2019-09-29 09:33:17', null=True)),
                ('description', models.TextField(blank=True, help_text='合同描述。示例：魏一二的测试合同', null=True)),
            ],
            options={
                'db_table': 'bm_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmEmailCode',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='用户邮箱验证码表ID。示例：5d68cb28cdb8ed13baebad9c', max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='用户邮箱。示例：wei.yier@21vianet.com', max_length=64)),
                ('code', models.CharField(help_text='用户邮箱验证码。示例：2d17540daa3f86dc2487e8d9a49b24ce|1567148838.0468245', max_length=64)),
            ],
            options={
                'db_table': 'bm_email_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmEnterprise',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='公司ID。示例：', max_length=64, primary_key=True, serialize=False)),
                ('enterprise_name', models.CharField(blank=True, help_text='公司名称。示例：北京世纪互联宽带数据中心有限公司', max_length=255, null=True)),
                ('abbreviation', models.TextField(blank=True, help_text='公司名称缩写。示例：世纪互联', null=True)),
                ('enterprise_number', models.CharField(blank=True, help_text='项目状态。示例：active/forbidden/deleted', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='描述。示例：世纪互联公司', null=True)),
                ('industry1', models.CharField(blank=True, help_text='公司行业1。示例：IT', max_length=255, null=True)),
                ('industry2', models.CharField(blank=True, help_text='公司行业1。示例：云计算', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='公司所属区域。示例：华北/华东', max_length=255, null=True)),
                ('sales', models.CharField(blank=True, help_text='公司销售姓名。示例：魏一二', max_length=255, null=True)),
                ('customer_service_name', models.CharField(blank=True, help_text='公司客服姓名。示例：魏一二', max_length=255, null=True)),
                ('payee', models.CharField(blank=True, help_text='公司收费姓名。示例：魏一二', max_length=255, null=True)),
                ('system_id', models.CharField(blank=True, help_text='暂时废弃字段。', max_length=255, null=True)),
                ('status', models.CharField(blank=True, help_text='公司状态。示例：active', max_length=64, null=True)),
                ('create_at', models.DateTimeField(blank=True, help_text='创建时间。示例：2019-09-29 09:33:17', null=True)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='更新时间。示例：2019-09-29 09:33:17', null=True)),
            ],
            options={
                'db_table': 'bm_enterprise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmMappingUserProject',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='用户项目关联表ID。示例：5d5faf299cf80f024abdf787', max_length=64, primary_key=True, serialize=False)),
                ('account_id', models.CharField(blank=True, help_text='用户ID。示例：5d5faf299cf80f024abdf787', max_length=64, null=True)),
                ('project_id', models.CharField(blank=True, help_text='项目ID。示例：5d5faf299cf80f024abdf787', max_length=64, null=True)),
                ('status', models.CharField(blank=True, help_text='关联状态。示例：active/deleted', max_length=64, null=True)),
            ],
            options={
                'db_table': 'bm_mapping_user_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmPhoneCode',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='用户手机号验证码表ID。示例：5d68cb28cdb8ed13baebad9c', max_length=64, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, help_text='手机号码。示例：18100009999', max_length=32, null=True)),
                ('code', models.CharField(blank=True, help_text='用户手机验证码ID。示例：123321', max_length=64, null=True)),
                ('ctime', models.CharField(blank=True, help_text='验证码时间戳。示例：1567148838.0468245', max_length=64, null=True)),
            ],
            options={
                'db_table': 'bm_phone_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmProject',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='项目ID。示例：7ae5a60714014778baddea703b85cd93', max_length=64, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, help_text='项目名称。示例：admin', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='项目描述。示例：管理项目', null=True)),
                ('status', models.CharField(blank=True, help_text='项目状态。示例：active/forbidden/deleted', max_length=255, null=True)),
                ('create_at', models.DateTimeField(blank=True, help_text='创建时间。示例：2019-09-29 09:33:17', null=True)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='更新时间。示例：2019-09-29 09:33:17', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间。示例：2019-09-29 09:33:17', null=True)),
            ],
            options={
                'db_table': 'bm_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmRequestInfo',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='用户请求信息表ID。示例：5d5faf299cf80f024abdf787', max_length=64, primary_key=True, serialize=False)),
                ('request_user', models.CharField(blank=True, help_text='接口请求用户。示例：admin', max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, help_text='接口请求方法。示例：GET', max_length=255, null=True)),
                ('request_url', models.TextField(blank=True, help_text='接口URL。示例：http://61.49.49.37:8002/account/query_all_account_info', null=True)),
                ('request_param', models.TextField(blank=True, help_text='接口参数。示例：<QueryDict: {}>', null=True)),
                ('reqeust_info', models.TextField(blank=True, help_text='接口信息。示例：<rest_framework.request.Request object at 0x7f2e0f3d97b8>', null=True)),
                ('request_result', models.TextField(blank=True, help_text='接口返回结果。示例：null', null=True)),
            ],
            options={
                'db_table': 'bm_request_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmRole',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='角色ID。示例：5cffb92400a6ba91f7c5bda6', max_length=64, primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, help_text='角色名称。示例：管理员', max_length=255, null=True)),
                ('role_limit', models.IntegerField(blank=True, help_text='角色权限值。示例：10', null=True)),
                ('description', models.TextField(blank=True, help_text='描述。示例：最高管理权限', null=True)),
                ('status', models.CharField(blank=True, help_text='角色状态。示例：active/deleted', max_length=64, null=True)),
                ('create_at', models.DateTimeField(blank=True, help_text='创建时间。示例：2019-09-29 09:33:17', null=True)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='更新时间。示例：2019-09-29 09:33:17', null=True)),
            ],
            options={
                'db_table': 'bm_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmUserInfo',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='用户id。示例：5cffb92400a6ba91f7c5bda6', max_length=64, primary_key=True, serialize=False)),
                ('account', models.CharField(help_text='用户邮箱。示例：wei.panlong@21vianet.com', max_length=64)),
                ('password', models.CharField(blank=True, help_text='用户密码。示例：asdqwe123', max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='手机号码。示例：18101029680', max_length=32, null=True)),
                ('name', models.CharField(blank=True, help_text='用户名称。示例：魏一二', max_length=255, null=True)),
                ('identity_name', models.CharField(blank=True, help_text='用户身份证姓名。示例：魏一二', max_length=255, null=True)),
                ('identity_card', models.CharField(blank=True, help_text='用户身份证号。示例：130182199910019999', max_length=18, null=True)),
                ('contact_address', models.TextField(blank=True, help_text='用户地址。示例：北京/朝阳区/世纪互联', null=True)),
                ('application_industry', models.CharField(blank=True, help_text='应用信息。示例：IT/大数据', max_length=255, null=True)),
                ('user_agreement', models.BooleanField(blank=True, help_text='是否同意用户协议。示例：True/False', null=True)),
                ('user_agreement_at', models.DateTimeField(blank=True, help_text='同意用户协议时间。示例：2019-09-29 09:33:17', null=True)),
                ('status', models.CharField(blank=True, help_text='用户状态。示例：active/forbidden/deleted', max_length=11, null=True)),
                ('description', models.TextField(blank=True, help_text='用户描述。示例：描述', null=True)),
                ('create_at', models.DateTimeField(blank=True, help_text='创建时间。示例：2019-09-29 09:33:17', null=True)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='更新时间。示例：2019-09-29 09:33:17', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='删除时间。示例：2019-09-29 09:33:17', null=True)),
            ],
            options={
                'db_table': 'bm_userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmUsertoken',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='用户登录验证码表ID。示例：5cffb92400a6ba91f7c5bda6', max_length=64, primary_key=True, serialize=False)),
                ('account_id', models.CharField(help_text='用户ID。示例：5cffb92400a6ba91f7c5bda6', max_length=64, unique=True)),
                ('account', models.CharField(help_text='用户邮箱。示例：wei.yier@21vianet.com', max_length=64, unique=True)),
                ('token', models.CharField(help_text='用户登录验证码ID。示例：fdade4f221165db56e4299f4bcd8f402|1569489431.1128526', max_length=64)),
            ],
            options={
                'db_table': 'bm_usertoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BmVerifyCode',
            fields=[
                ('id', models.CharField(default=common.lark_common.random_object_id.gen_random_object_id, help_text='用户手机、邮箱验证码表ID。示例：5d5faf299cf80f024abdf787', max_length=64, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, help_text='用户手机号。示例：18100009999', max_length=32, null=True)),
                ('email', models.CharField(blank=True, help_text='用户邮箱。示例：wei.yier@21vianet.com', max_length=255, null=True)),
                ('code', models.CharField(blank=True, help_text='用户邮箱或手机验证码。示例：973884', max_length=64, null=True)),
                ('ctime', models.CharField(blank=True, help_text='验证码时间戳。示例：1567148838.0468245', max_length=64, null=True)),
            ],
            options={
                'db_table': 'bm_verify_code',
                'managed': False,
            },
        ),
    ]
